/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: b111f3c25a071e66c23961eefc16cd94)
interface __BaseEnv_Env {
	AUTH_LIMITER: RateLimit;
	ALLOWED_ORIGINS: "https://deepboard.pages.dev,http://localhost:60379";
	BOARD_PASSWORD: string;
	PASS_SECRET: string;
	BOARD_ROOM: DurableObjectNamespace<import("./src/index").BoardRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "BoardRoom";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGINS" | "BOARD_PASSWORD" | "PASS_SECRET">> {}
}
declare module "*.txt" {
	const value: string;
	export default value;
}
declare module "*.html" {
	const value: string;
	export default value;
}
declare module "*.sql" {
	const value: string;
	export default value;
}
declare module "*.bin" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
declare module "*.wasm?module" {
	const value: WebAssembly.Module;
	export default value;
}